/* Create a table that will be used to store labeling information generated by our machine learning models.
   A label record should associated with an event, contain information about the model that labeled it, the time it
   was added to the database, a cavity label, a fault type label, and the numerical confidences associated with the two
   labels.

   Each event should only have a single label.  Reports may search this table by labels (all cav 1 faults) and/or
   confidences (everything over 0.50) so index accordingly.
 */
CREATE TABLE label (
     label_id BIGINT NOT NULL AUTO_INCREMENT,
     event_id BIGINT(20) NOT NULL,
     model_name VARCHAR(127) NOT NULL,
     label_time_utc DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     cavity_label VARCHAR(127) NOT NULL,
     cavity_confidence DECIMAL(3,2) UNSIGNED ZEROFILL,
     fault_label VARCHAR(127) NOT NULL,
     fault_confidence DECIMAL(3,2) UNSIGNED ZEROFILL,
     UNIQUE KEY `event_id` (event_id),
     INDEX i_cavity_label (cavity_label),
     INDEX i_cavity_confidence (cavity_confidence),
     INDEX i_fault_label (fault_label),
     INDEX i_fault_confidence (fault_confidence),
     PRIMARY KEY (label_id),
     FOREIGN KEY (event_id)
         REFERENCES event (event_id)
         ON DELETE CASCADE
) ENGINE=InnoDB;